// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Account struct {
	ID              int32     `json:"id"`
	AccountHolderID int32     `json:"account_holder_id"`
	AccountNumber   int64     `json:"account_number"`
	Balance         string    `json:"balance"`
	CreatedAt       time.Time `json:"created_at"`
}

type AccountHolder struct {
	ID        int32     `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
}
